export const OWMAPI_KEY = `${process.env.REACT_APP_OWMAPI_KEY}`

export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR'

export const GET_FORECAST_REQUEST = 'GET_FORECAST_REQUEST'
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS'
export const GET_FORECAST_ERROR = 'GET_FORECAST_ERROR'

export const GET_CITY = 'GET_CITY'